version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db_10
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env
  redis:
    image: redis:7
    container_name: redis_10
    command: --port 5370
    expose:
      - 5370
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: api_10
    depends_on:
      - db
      - redis
    ports:
      - 8080:8080
  celery:
    build:
      context: .
    container_name: celery_10
    env_file:
      - .env
    command: ["/lab3/docker/celery.sh"]
    depends_on:
      - app
      - redis
      - db
