"""nullable

Revision ID: 1aeec21688ad
Revises: d384cf963d60
Create Date: 2024-08-19 16:31:51.137742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1aeec21688ad'
down_revision: Union[str, None] = 'd384cf963d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('book', 'publisher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'publisher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('book', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
