"""nullable for acception

Revision ID: 942c00595baa
Revises: 1aeec21688ad
Create Date: 2024-08-19 17:15:17.234005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '942c00595baa'
down_revision: Union[str, None] = '1aeec21688ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishlist', 'is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishlist', 'is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
