"""aboba

Revision ID: 98266c4136aa
Revises: 9b2c2cbc730b
Create Date: 2024-08-24 22:09:53.761962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '98266c4136aa'
down_revision: Union[str, None] = '9b2c2cbc730b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('aboba', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist', 'aboba')
    # ### end Alembic commands ###
