"""w

Revision ID: 9b2c2cbc730b
Revises: 38dd0de00227
Create Date: 2024-08-24 22:01:35.652422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b2c2cbc730b'
down_revision: Union[str, None] = '38dd0de00227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist', 'aboba')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('aboba', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
