"""skill dropped

Revision ID: d384cf963d60
Revises: 76794b5798f7
Create Date: 2024-08-18 15:32:53.162636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd384cf963d60'
down_revision: Union[str, None] = '76794b5798f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
